### ISSUE TITLE
Move build-helper-maven-plugin and avro-maven-plugin declarations to parent poms

### ISSUE THREAD

**Issue by lukdumi** [openaire/iis#302] opened 2016-04-06 05:32 UTC

**Comment by marekhorst** [comment] 2016-04-22 11:08
I have explored this issue and here is the conclusion:

### 1) `avro-maven-plugin`

It turned out there are 4 modules with `avro-maven-plugin` defined:
- `iis-wf-preprocessing`
- `iis-wf-referenceextraction`
- `iis-wf-metadataextraction`
- `iis-wf-citationmatching`

which do not have any avro schemas defined so we could drop redundant plugin definition.

Currently we do have shared configuration for this plugin in top `pom.xml` file in `pluginManagement` section. The problem is only 6 modules:
- `iis-3rdparty-avrojsoncoders`
- `iis-common`
- `iis-schemas`
- `iis-wf-collapsers`
- `iis-wf-core-examples`
- `iis-wf-primary`

out of almost 30 in total have avro schemas defined and only 3 of those 6 share the same configuration defined in top `pom.xml` file.

**Recommendation**: remove shared configuration in root `pom.xml` file and define it explicitly in 6 modules. This would allow avoiding #234 kind of issues we stuck on recently at least twice.

### 2) `build-helper-maven-plugin`

In some way it is bound to `avro-maven-plugin` because it attaches avro classes generated with `avro-maven-plugin` to build path.

It turned out there are 5 modules with `build-helper-maven-plugin` defined:
- `iis-wf-preprocessing`
- `iis-wf-referenceextraction`
- `iis-wf-metadataextraction`
- `iis-wf-citationmatching`
- `iis-wf-documentsclassification`

which do not have any avro schemas defined so we could drop redundant plugin definition.

Currently we do not have shared configuration for this plugin. It is defined explicitly in 6 modules out of almost 30.

**Recommendation**: Since it is bound to `avro-maven-plugin` - leave it as it is (apart from removing redundant plugin definitions).

**Comment by marekhorst** [comment] 2016-04-22 11:08
@mpol before I move on with applying commit and creating pull request - what do you think about this solution?

**Comment by mpol** [comment] 2016-04-22 15:36
I don't know, really. This should work, but I'm still not sure why really the configurations have to be different (and not default).

**Comment by mpol** [comment] 2016-04-25 08:38
@marekhorst Why is this task assigned to me?

**Comment by marekhorst** [comment] 2016-04-25 09:11
> @marekhorst Why is this task assigned to me?

Just wanted to indicate I am awaiting your reply. I am reassigning this issue.

**Comment by marekhorst** [comment] 2016-04-25 17:00
We also need to define `build-helper-maven-plugin` version explicitly (to latest `1.10`) in `pluginManagement` section of root `pom.xml` file. Currently it is not specified which is not recommended.

**Comment by marekhorst** [comment] 2016-04-25 18:04
There is one more thing we could do: move all avro files to:
- `${basedir}/src/main/avro`
- `${basedir}/src/test/avro`

and expect output directory to be:
- `${project.build.directory}/generated-sources/avro`
- `${project.build.directory}/generated-test-sources/avro`

accordingly. 

This way we could:
- separate avro sources from other resources
- rely on default maven configuration (simplified execution configuration in `pom.xml` files)

**Closed** 2016-04-26 12:33 UTC
Labels: activity: refactor, functionality: core
